// Library related constants
export const LIBRARY_ADD_BOOK = 'LIBRARY_ADD_BOOK';
export const LIBRARY_REMOVE_BOOK = 'LIBRARY_REMOVE_BOOK';
export const LIBRARY_UPDATE_BOOK = 'LIBRARY_UPDATE_BOOK';

// Filtered view related constants
export const VIEW_SELECT_ALL = 'VIEW_SELECT_ALL';
export const VIEW_SELECT_FAV = 'VIEW_SELECT_FAV';
export const VIEW_SELECT_READ = 'VIEW_SELECT_READ';
export const VIEW_SELECT_LOANED = 'VIEW_SELECT_LOANED';
export const VIEW_ADD_TO_CURRENT = 'VIEW_ADD_TO_CURRENT';
export const VIEW_REMOVE_FROM_CURRENT = 'VIEW_REMOVE_FROM_CURRENT';
